name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to PythonAnywhere
      run: |
        # Install required packages for API calls
        pip install requests
        
        # Create deployment script
        cat << 'EOF' > deploy.py
        import requests
        import os
        
        username = "${{ secrets.PYTHONANYWHERE_USERNAME }}"
        token = "${{ secrets.PYTHONANYWHERE_API_TOKEN }}"
        domain = "${{ secrets.PYTHONANYWHERE_DOMAIN }}"
        
        # Pull latest code
        response = requests.post(
            f'https://www.pythonanywhere.com/api/v0/user/{username}/consoles/',
            headers={'Authorization': f'Token {token}'},
            json={
                'executable': 'bash',
                'arguments': ['-c', f'cd /home/{username}/your-repo-name && git pull origin main && /home/{username}/.virtualenvs/myflaskapp/bin/pip install -r requirements.txt']
            }
        )
        print(f"Console creation: {response.status_code}")
        
        # Reload web app
        response = requests.post(
            f'https://www.pythonanywhere.com/api/v0/user/{username}/webapps/{domain}/reload/',
            headers={'Authorization': f'Token {token}'}
        )
        print(f"Reload status: {response.status_code}")
        if response.status_code == 200:
            print("✅ Deployment successful!")
        else:
            print(f"❌ Deployment failed: {response.text}")
        EOF
        
        # Run deployment
        python deploy.py
